# FreeBSD documentation

baseURL = "http://127.0.0.1:5500"
title = "FreeBSD 中文文档"
copyright = "BSD 2-clause 'Simplified' License"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true
disablePathToLower = true
theme = "beastie"
disableKinds = [ "taxonomy", "taxonomyTerm" ]
authors = [ "fiercex@outlook.com" ]
ignoreFiles = [ "chapter.adoc$", "contrib-386bsd.adoc$", "contrib-additional.adoc$", "contrib-committers.adoc$", "contrib-corealumni.adoc$", "contrib-develalumni.adoc$", "contrib-develinmemoriam.adoc$", "contrib-portmgralumni.adoc$", "\\.po$" ]
enableRobotsTXT = true
enableGitInfo = true
timeout = 180000

[params]
  websiteURL = "https://free.bsd-doc.org"
  description = "FreeBSD 中文文档"
  isOnline = true
  search = true
  editBaseUrl = "https://github.com/fierceX/freebsd-doc-cn"
  # downloadBaseUrl = "https://download.freebsd.org/doc/"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
    osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|LOAD_PATH|RUBYLIB)$"]
  [security.funcs]
    getenv = ["^HUGO_"]
  [security.http]
    methods = ["(?i)GET|POST"]
    urls = [".*"]

[markup.asciidocExt]
    extensions = ["man-macro", "inter-document-references-macro", "cross-document-references-macro", "sectnumoffset-treeprocessor", "packages-macro", "git-macro"]
    [markup.asciidocExt.attributes]
      env-beastie = true
      isOnline = true
      skip-front-matter = true
      sectanchors = "after"

[outputs]
home = [ "HTML","JSON"]