# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install po4a
        run: |
              sudo apt update
              sudo apt install po4a
      - name: Set Python
        uses: actions/setup-python@v4.3.0
        with: 
          python-version: '3.9'
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: install pkg
        run: |
          pip install OpenAI msgpack deepl polib
          gem install rouge
      - name: set build env
        run: |
              sudo apt install asciidoctor
              sudo apt install hugo
      - name: up tmx
        run: bash tools/up_tmx.sh
      - name: push tmx
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              git config --global user.email "fiercex@outlook.com"
              git config --global user.name "github actions"
              set +e
              git add tools/tmx.msg
              git commit -m "up tmx"
              git remote -v
              git push
              set -e
      - name: translate
        run: |
              bash tools/translate.sh website zh-cn books/handbook
      - name: auto_translate
        run: |
              bash tools/auto_translate.sh
              bash tools/translate.sh website zh-cn-auto books/handbook
      - name: push translate
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
              git config --global user.email "fiercex@outlook.com"
              git config --global user.name "github actions"
              set +e
              git add website
              git commit -m "up"
              git remote -v
              git push
              set -e
      - name: build
        run: |
              export RUBYLIB=$GITHUB_WORKSPACE/website/shared/lib
              cp -r website/shared shared
              cd website
              hugo -b 'https://free.bsd-doc.org'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
          publish_branch: bsd-doc
          keep_files: false
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: 'website/public'
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v1

      
      
